
package poslovnaxws.services.centralnabanka;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-26T01:29:42.294+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class CBAcknlowledge_CBAcknlowledgePort_Client {

    private static final QName SERVICE_NAME = new QName("PoslovnaXWS/services/centralnaBanka", "CBService");

    private CBAcknlowledge_CBAcknlowledgePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CBService ss = new CBService(wsdlURL, SERVICE_NAME);
        CBAcknlowledge port = ss.getCBAcknlowledgePort();  
        
        {
        System.out.println("Invoking sendMT900...");
        poslovnaxws.poruke.MT900 _sendMT900__return = port.sendMT900();
        System.out.println("sendMT900.result=" + _sendMT900__return);


        }
        {
        System.out.println("Invoking sendMT910...");
        poslovnaxws.poruke.MT910 _sendMT910__return = port.sendMT910();
        System.out.println("sendMT910.result=" + _sendMT910__return);


        }

        System.exit(0);
    }

}
