
package poslovnaxws.services.centralnabanka;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-26T01:29:42.629+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class CBAcknlowledge_CBAcknlowledgePort_Server{

    protected CBAcknlowledge_CBAcknlowledgePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CBClearingImpl();
        String address = "http://localhost:8080/PoslovnaXWS/CBAcknlowledge";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CBAcknlowledge_CBAcknlowledgePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
