
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package poslovnaxws.services.centralnabanka;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-26T01:29:42.541+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "CBService",
                      portName = "CBAcknlowledgePort",
                      targetNamespace = "PoslovnaXWS/services/centralnaBanka",
                      wsdlLocation = "file:/C:/Users/Lazar/Desktop/Faks/PI/PoslovnaXWS/CentralnaBanka/web/WEB-INF/wsdl/CentralnaBanka.wsdl",
                      endpointInterface = "poslovnaxws.services.centralnabanka.CBAcknlowledge")
                      
public class CBAcknlowledgeImpl implements CBAcknlowledge {

    private static final Logger LOG = Logger.getLogger(CBAcknlowledgeImpl.class.getName());

    /* (non-Javadoc)
     * @see poslovnaxws.services.centralnabanka.CBAcknlowledge#sendMT900(*
     */
    public poslovnaxws.poruke.MT900 sendMT900() { 
        LOG.info("Executing operation sendMT900");
        try {
            poslovnaxws.poruke.MT900 _return = new poslovnaxws.poruke.MT900();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see poslovnaxws.services.centralnabanka.CBAcknlowledge#sendMT910(*
     */
    public poslovnaxws.poruke.MT910 sendMT910() { 
        LOG.info("Executing operation sendMT910");
        try {
            poslovnaxws.poruke.MT910 _return = new poslovnaxws.poruke.MT910();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
