package poslovnaxws.services.centralnabanka;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-26T01:29:42.610+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "PoslovnaXWS/services/centralnaBanka", name = "CBAcknlowledge")
@XmlSeeAlso({poslovnaxws.banke.ObjectFactory.class, poslovnaxws.poruke.ObjectFactory.class, poslovnaxws.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CBAcknlowledge {

    @WebMethod
    @WebResult(name = "MT900", targetNamespace = "PoslovnaXWS/Poruke", partName = "mt900")
    public poslovnaxws.poruke.MT900 sendMT900();

    @WebMethod
    @WebResult(name = "MT910", targetNamespace = "PoslovnaXWS/Poruke", partName = "mt910")
    public poslovnaxws.poruke.MT910 sendMT910();
}
