
package poslovnaxws.services.centralnabanka;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-26T01:29:42.495+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class CBClearing_CBClearingPort_Client {

    private static final QName SERVICE_NAME = new QName("PoslovnaXWS/services/centralnaBanka", "CBService");

    private CBClearing_CBClearingPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CBService ss = new CBService(wsdlURL, SERVICE_NAME);
        CBClearing port = ss.getCBClearingPort();  
        
        {
        System.out.println("Invoking receiveMT102Clearing...");
        poslovnaxws.poruke.MT102 _receiveMT102Clearing_mt102 = new poslovnaxws.poruke.MT102();
        poslovnaxws.common.Status _receiveMT102Clearing__return = port.receiveMT102Clearing(_receiveMT102Clearing_mt102);
        System.out.println("receiveMT102Clearing.result=" + _receiveMT102Clearing__return);


        }
        {
        System.out.println("Invoking receiveMT103Clearing...");
        poslovnaxws.poruke.MT103 _receiveMT103Clearing_mt103 = new poslovnaxws.poruke.MT103();
        poslovnaxws.common.Status _receiveMT103Clearing__return = port.receiveMT103Clearing(_receiveMT103Clearing_mt103);
        System.out.println("receiveMT103Clearing.result=" + _receiveMT103Clearing__return);


        }

        System.exit(0);
    }

}
