
package poslovnaxws.services.centralnabanka;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-26T01:29:42.632+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class CBRTGS_CBRTGSPort_Server{

    protected CBRTGS_CBRTGSPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CBRTGSImpl();
        String address = "http://localhost:8080/PoslovnaXWS/CBRTGS";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CBRTGS_CBRTGSPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
