
package poslovnaxws.services.centralnabanka;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-14T16:24:55.516+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class CentralnaBanka_CentralnaBankaPort_Client {

    private static final QName SERVICE_NAME = new QName("PoslovnaXWS/services/centralnaBanka", "CBService");

    private CentralnaBanka_CentralnaBankaPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CBService ss = new CBService(wsdlURL, SERVICE_NAME);
        CentralnaBanka port = ss.getCentralnaBankaPort();  
        
        {
        System.out.println("Invoking receiveMT103...");
        poslovnaxws.poruke.MT103 _receiveMT103_mt103 = new poslovnaxws.poruke.MT103();
        poslovnaxws.common.Status _receiveMT103__return = port.receiveMT103(_receiveMT103_mt103);
        System.out.println("receiveMT103.result=" + _receiveMT103__return);


        }
        {
        System.out.println("Invoking receiveMT102...");
        poslovnaxws.poruke.MT102 _receiveMT102_mt102 = new poslovnaxws.poruke.MT102();
        poslovnaxws.common.Status _receiveMT102__return = port.receiveMT102(_receiveMT102_mt102);
        System.out.println("receiveMT102.result=" + _receiveMT102__return);


        }

        System.exit(0);
    }

}
