package poslovnaxws.services.centralnabanka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-14T16:24:55.799+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "PoslovnaXWS/services/centralnaBanka", name = "CentralnaBanka")
@XmlSeeAlso({poslovnaxws.banke.ObjectFactory.class, poslovnaxws.common.ObjectFactory.class, poslovnaxws.poruke.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CentralnaBanka {

    @WebResult(name = "status", targetNamespace = "PoslovnaXWS/Common", partName = "mt103Response")
    @WebMethod
    public poslovnaxws.common.Status receiveMT103(
        @WebParam(partName = "mt103", name = "MT103", targetNamespace = "PoslovnaXWS/Poruke")
        poslovnaxws.poruke.MT103 mt103
    );

    @WebResult(name = "status", targetNamespace = "PoslovnaXWS/Common", partName = "mt102Response")
    @WebMethod
    public poslovnaxws.common.Status receiveMT102(
        @WebParam(partName = "mt102", name = "MT102", targetNamespace = "PoslovnaXWS/Poruke")
        poslovnaxws.poruke.MT102 mt102
    );
    
    @WebResult(name = "status", targetNamespace = "PoslovnaXWS/Common", partName = "clearingResponse")
    @WebMethod
    public poslovnaxws.common.Status doClearing();
}
