//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.27 at 02:40:02 AM CEST 
//

package poslovnaxws.banke;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import entity.iface.Identifiable;
import poslovnaxws.common.TBanka;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{PoslovnaXWS/Common}TBanka">
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "banka")
public class Banka implements Identifiable {
	@XmlElement(name="tbanka")
	protected TBanka banka;
	
	@XmlAttribute(name = "id")
	protected Long id;

	@Override
	public String getId() {
		return String.valueOf(banka.getSifra());
	}

	@Override
	public void setId(String value) {
		banka.setSifra(Integer.parseInt(value));
		id = (long) banka.getSifra();
		
	}

	public TBanka getBanka() {
		return banka;
	}

	public void setBanka(TBanka banka) {
		this.banka = banka;
	}

}
