package poslovnaxws.services.banka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-21T17:44:10.699+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "PoslovnaXWS/services/banka", name = "BankaServiceMessages")
@XmlSeeAlso({poslovnaxws.banke.ObjectFactory.class, poslovnaxws.poruke.ObjectFactory.class, poslovnaxws.common.ObjectFactory.class, poslovnaxws.fakture.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BankaServiceMessages {

    @WebMethod
    @WebResult(name = "MT103", targetNamespace = "PoslovnaXWS/Poruke", partName = "mt103")
    public poslovnaxws.poruke.MT103 sendMT103();

    @WebMethod
    @WebResult(name = "MT102", targetNamespace = "PoslovnaXWS/Poruke", partName = "mt102")
    public poslovnaxws.poruke.MT102 sendMT102();

    @WebMethod
    @WebResult(name = "status", targetNamespace = "PoslovnaXWS/Common", partName = "notification")
    public poslovnaxws.common.Status receiveMT103(
        @WebParam(partName = "mt103", name = "MT103", targetNamespace = "PoslovnaXWS/Poruke")
        poslovnaxws.poruke.MT103 mt103
    );

    @WebMethod
    @WebResult(name = "status", targetNamespace = "PoslovnaXWS/Common", partName = "notification")
    public poslovnaxws.common.Status receiveMT102(
        @WebParam(partName = "mt102", name = "MT102", targetNamespace = "PoslovnaXWS/Poruke")
        poslovnaxws.poruke.MT102 mt102
    );

    @WebMethod
    @WebResult(name = "status", targetNamespace = "PoslovnaXWS/Common", partName = "notification")
    public poslovnaxws.common.Status receiveMT900(
        @WebParam(partName = "mt900", name = "MT900", targetNamespace = "PoslovnaXWS/Poruke")
        poslovnaxws.poruke.MT9 mt900
    );

    @WebMethod
    @WebResult(name = "status", targetNamespace = "PoslovnaXWS/Common", partName = "notification")
    public poslovnaxws.common.Status receiveMT910(
        @WebParam(partName = "mt910", name = "MT910", targetNamespace = "PoslovnaXWS/Poruke")
        poslovnaxws.poruke.MT9 mt910
    );

    @WebMethod
    @WebResult(name = "zahtevZaIzvod", targetNamespace = "PoslovnaXWS/Banke", partName = "zahtevZaIzvod")
    public poslovnaxws.banke.ZahtevZaIzvod zahtevZaIzvod() throws NotificationMessage;
}
