
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package poslovnaxws.services.banka;

import java.util.logging.Logger;

import poslovnaxws.common.Status;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-05-21T17:44:10.658+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "BankaService",
                      portName = "BankaServicePort",
                      targetNamespace = "PoslovnaXWS/services/banka",
                      wsdlLocation = "file:/C:/Users/Lazar/Desktop/Faks/PI/PoslovnaXWS/CentralnaBanka/WEB-INF/wsdl/Banka.wsdl",
                      endpointInterface = "poslovnaxws.services.banka.BankaServiceMessages")
                      
public class BankaServiceMessagesImpl implements BankaServiceMessages {

    private static final Logger LOG = Logger.getLogger(BankaServiceMessagesImpl.class.getName());

    /* (non-Javadoc)
     * @see poslovnaxws.services.banka.BankaServiceMessages#sendMT103(*
     */
    public poslovnaxws.poruke.MT103 sendMT103() { 
        LOG.info("Executing operation sendMT103");
        try {
            poslovnaxws.poruke.MT103 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see poslovnaxws.services.banka.BankaServiceMessages#sendMT102(*
     */
    public poslovnaxws.poruke.MT102 sendMT102() { 
        LOG.info("Executing operation sendMT102");
        try {
            poslovnaxws.poruke.MT102 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see poslovnaxws.services.banka.BankaServiceMessages#receiveMT103(poslovnaxws.poruke.MT103  mt103 )*
     */
    public poslovnaxws.common.Status receiveMT103(poslovnaxws.poruke.MT103 mt103) { 
        LOG.info("Executing operation receiveMT103");
        System.out.println(mt103);
        try {
            poslovnaxws.common.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see poslovnaxws.services.banka.BankaServiceMessages#receiveMT102(poslovnaxws.poruke.MT102  mt102 )*
     */
    public poslovnaxws.common.Status receiveMT102(poslovnaxws.poruke.MT102 mt102) { 
        LOG.info("Executing operation receiveMT102");
        System.out.println(mt102);
        try {
            poslovnaxws.common.Status _return = new poslovnaxws.common.Status();
            _return.setKod(0);
            _return.setOpis("OK");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see poslovnaxws.services.banka.BankaServiceMessages#receiveMT900(poslovnaxws.poruke.MT9  mt900 )*
     */
    public poslovnaxws.common.Status receiveMT900(poslovnaxws.poruke.MT9 mt900) { 
        LOG.info("Executing operation receiveMT900");
        System.out.println(mt900);
        try {
            poslovnaxws.common.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see poslovnaxws.services.banka.BankaServiceMessages#receiveMT910(poslovnaxws.poruke.MT9  mt910 )*
     */
    public poslovnaxws.common.Status receiveMT910(poslovnaxws.poruke.MT9 mt910) { 
        LOG.info("Executing operation receiveMT910");
        System.out.println(mt910);
        try {
            poslovnaxws.common.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see poslovnaxws.services.banka.BankaServiceMessages#zahtevZaIzvod(*
     */
    public poslovnaxws.banke.ZahtevZaIzvod zahtevZaIzvod() throws NotificationMessage    { 
        LOG.info("Executing operation zahtevZaIzvod");
        try {
            poslovnaxws.banke.ZahtevZaIzvod _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NotificationMessage("notificationMessage...");
    }

}
