//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.04 at 10:41:14 PM CEST 
//


package poslovnaxws.poruke;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the poslovnaxws.poruke package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: poslovnaxws.poruke
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MT102 }
     * 
     */
    public MT102 createMT102() {
        return new MT102();
    }

    /**
     * Create an instance of {@link MT910 }
     * 
     */
    public MT910 createMT910() {
        return new MT910();
    }

    /**
     * Create an instance of {@link MT900 }
     * 
     */
    public MT900 createMT900() {
        return new MT900();
    }

    /**
     * Create an instance of {@link MT103 }
     * 
     */
    public MT103 createMT103() {
        return new MT103();
    }

    /**
     * Create an instance of {@link MT102 .Uplate }
     * 
     */
    public MT102 .Uplate createMT102Uplate() {
        return new MT102 .Uplate();
    }

}
